name: Sonic

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Dependencies
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: node-modules-${{hashFiles('**/package-lock.json')}}
        restore-keys: |
          node-modules-

    - name: install
      run: npm i

    - name: test
      run: npm run test
      env:
        CI: true

