name: sonic

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [client, react, server]

    steps:
    - uses: actions/checkout@v3

    - name: node 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: dependencies cache
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: node-modules-${{hashFiles('**/package-lock.json')}}
        restore-keys: |
          node-modules-

    - name: install
      working-directory: './packages/${{matrix.service}}'
      run: npm i

    - name: test
      working-directory: './packages/${{matrix.service}}'
      run: npm run test
      env:
        CI: true

